// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Luna_Surveyor","status":false,"description":"An extension to the MV/MZ core that allows you to modify the in game ui\nas a UI Kit <Luna_Surveyor>.\"","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"SNBR_CustomMenu","status":false,"description":"Custom main menu","parameters":{"ChaptersMenuItem":"Chapters","Back":"Back","Chapters":"[]"}}
];
